<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>AutoriaStore.API</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.12.43" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\AutoriaStore.Application.csproj" />
    <ProjectReference Include="..\Infrastructure\AutoriaStore.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Middlewares\" />
  </ItemGroup>

</Project>
