<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Domain\AutoriaStore.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>AutoriaStore.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
